import { AfterViewInit, ElementRef, OnChanges, SimpleChanges, ViewContainerRef } from '@angular/core';
import { GraphContext } from './GraphService';
export declare class Graph implements AfterViewInit, OnChanges {
    private context;
    data?: any;
    height?: number;
    width?: number;
    animate?: boolean | object;
    fitView?: boolean;
    fitViewPadding?: any;
    type?: any;
    layout?: any;
    onMouseDown?: any;
    onMouseMove?: any;
    onMouseUp?: any;
    onClick?: any;
    onDbClick?: any;
    onTouchStart?: any;
    onTouchMove?: any;
    onTouchEnd?: any;
    onPlotEnter?: any;
    onPlotMove?: any;
    onPlotLeave?: any;
    onPlotClick?: any;
    onPlotDbClick?: any;
    onAfterchange?: any;
    onDragstart?: any;
    onDrag?: any;
    onDragend?: any;
    graphDiv?: any;
    private componentId;
    private elem;
    constructor(context: GraphContext, elem: ElementRef, vcRef: ViewContainerRef);
    ngAfterViewInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    private combineViewConfig;
    private combineGraphConfig;
    private convertValueToNum;
    private combineContentConfig;
    private getProps;
    private getComponentName;
    private initGraph;
    private renderGraph;
}
